import HangoutLow from './PurdueMixedMediaClubHangout.jpg?w=200&blur=4&format=webp&imagetools';
import HangoutHigh from './PurdueMixedMediaClubHangout.jpg?w=4096&quality=95&format=webp&imagetools';
import CampingLow from './PurdueMixedMediaClubCamping.jpg?w=200&blur=4&format=webp&imagetools';
import CampingHigh from './PurdueMixedMediaClubCamping.jpg?w=4096&quality=95&format=webp&imagetools';
import EthanTwuBTSLow from './EthanTwuBTS.jpg?w=200&blur=4&format=webp&imagetools';
import EthanTwuBTSHigh from './EthanTwuBTS.jpg?w=4096&quality=95&format=webp&imagetools';
import JonathanChanBTSLow from './JonathanChanBTS.jpg?w=200&blur=4&format=webp&imagetools';
import JonathanChanBTSHigh from './JonathanChanBTS.jpg?w=4096&quality=95&format=webp&imagetools';
import FilmWorkshopBTSLow from './filmWorkshopBTS.jpg?w=200&blur=4&format=webp&imagetools';
import FilmWorkshopBTSHigh from './filmWorkshopBTS.jpg?w=4096&quality=95&format=webp&imagetools';
import CircularStarTrailLow from './CircularStarTrail.jpg?w=200&blur=4&format=webp&imagetools';
import CircularStarTrailHigh from './CircularStarTrail.jpg?w=4096&quality=95&format=webp&imagetools';
import BridgeButBTSLow from './BridgeButBTS.jpg?w=100&blur=4&format=webp&imagetools';
import BridgeButBTSHigh from './BridgeButBTS.jpg?w=2048&quality=95&format=webp&imagetools';
import BridgeButBTS2Low from './BridgeButBTS2.jpg?w=100&blur=4&format=webp&imagetools';
import BridgeButBTS2High from './BridgeButBTS2.jpg?w=2048&quality=95&format=webp&imagetools';
import BridgePhotoETLow from './BridgePhotoET.jpg?w=100&blur=4&format=webp&imagetools';
import BridgePhotoETHigh from './BridgePhotoET.jpg?w=2048&quality=95&format=webp&imagetools';
import EthanBTSDeanRKLow from './EthanBTSDeanRK.jpg?w=100&blur=4&format=webp&imagetools';
import EthanBTSDeanRKHigh from './EthanBTSDeanRK.jpg?w=2048&quality=95&format=webp&imagetools';
import DeanRKBTSLow from './DeanRKBTS.jpg?w=100&blur=4&format=webp&imagetools';
import DeanRKBTSHigh from './DeanRKBTS.jpg?w=2048&quality=95&format=webp&imagetools';

export const hangout = { lowSrc: HangoutLow, src: HangoutHigh };
export const camping = { lowSrc: CampingLow, src: CampingHigh };
export const ethanTwuBTS = { lowSrc: EthanTwuBTSLow, src: EthanTwuBTSHigh };
export const jonathanChanBTS = { lowSrc: JonathanChanBTSLow, src: JonathanChanBTSHigh };
export const filmWorkshopBTS = { lowSrc: FilmWorkshopBTSLow, src: FilmWorkshopBTSHigh };
export const circularStarTrail = { lowSrc: CircularStarTrailLow, src: CircularStarTrailHigh };
export const bridgeButBTS = { lowSrc: BridgeButBTSLow, src: BridgeButBTSHigh };
export const bridgeButBTS2 = { lowSrc: BridgeButBTS2Low, src: BridgeButBTS2High };
export const bridgePhotoET = { lowSrc: BridgePhotoETLow, src: BridgePhotoETHigh };
export const ethanBTSDeanRK = { lowSrc: EthanBTSDeanRKLow, src: EthanBTSDeanRKHigh };
export const deanRKBTS = { lowSrc: DeanRKBTSLow, src: DeanRKBTSHigh };
